sudo: required
language: python
python:
  - "3.6"
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "jmlinder"
  env: "jmlinder-dev"
  bucket_name:
    secure: "elasticbeanstalk-us-east-1-835178066609"
  bucket_path:
    secure: "jmlinder"
  on:
    branch: travis_config
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: $AWS_SECRET_KEY
