sudo: required
language: python
python: "3.6"
install: pip install -r requirements-dev.txt
services: postgres
env:
  global: PGPORT=5432
before_script:
  - psql -c 'create database jmlinder;' -U postgres
  - psql -c 'CREATE ROLE joe SUPERUSER LOGIN;' -U postgres
script: pytest
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "jmlinder"
  env:
    ELASTIC_BEANSTALK_ENV: "jmlinder-staging"
    global:
      ADMIN:
        secure: "$ADMIN"
      DJANGO_SETTINGS_MODULE:
        secure: "$DJANGO_SETTINGS_MODULE"
      EB_ENV_URL:
        secure: "$EB_ENV_URL"
      EB_STAGE_ENV:
        secure: "$EB_STAGE_ENV"
      SECRET_KEY:
        secure: "$SECRET_KEY"
      SITE_URL:
        secure: "$SITE_URL"
  bucket_name:
    secure: "$BUCKET_NAME"
  bucket_path:
    secure: "$BUCKET_PATH"
  on:
    branch: travis_config
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
